create extension if not exists pgcrypto;

create type public.user_role as enum ('admin');
create type public.order_type as enum ('delivery', 'dine_in');
create type public.order_status as enum ('new', 'accepted', 'preparing', 'ready', 'served', 'completed', 'cancelled');
create type public.promotion_status as enum ('draft', 'active', 'expired');

create sequence public.delivery_order_seq;
create sequence public.dine_in_order_seq;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role public.user_role not null default 'admin',
  display_name text,
  created_at timestamptz not null default now()
);

create table public.categories (
  id text primary key,
  slug text not null unique,
  name_ru text not null,
  name_kk text,
  sort_order integer not null default 0,
  is_visible boolean not null default true,
  is_archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.menu_items (
  id text primary key,
  category_id text not null references public.categories(id),
  slug text not null unique,
  name_ru text not null,
  name_kk text,
  description_ru text,
  description_kk text,
  price integer not null check (price >= 0),
  image_url text,
  sort_order integer not null default 0,
  is_available boolean not null default true,
  is_visible_public boolean not null default true,
  is_visible_dine_in boolean not null default true,
  is_featured boolean not null default false,
  is_spicy boolean not null default false,
  is_new boolean not null default false,
  is_archived boolean not null default false,
  needs_review boolean not null default false,
  piece_count integer,
  source text not null default 'menu_pdf',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.set_items (
  id bigint generated by default as identity primary key,
  set_id text not null references public.menu_items(slug) on update cascade on delete cascade,
  item_slug text not null references public.menu_items(slug) on update cascade,
  quantity integer not null check (quantity > 0),
  unique (set_id, item_slug)
);

create table public.tables (
  id text primary key,
  label text not null unique,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  is_archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique,
  order_type public.order_type not null,
  status public.order_status not null default 'new',
  customer_name text,
  customer_phone text,
  delivery_address text,
  entrance text,
  floor text,
  apartment text,
  table_id text references public.tables(id),
  comment text,
  subtotal integer not null check (subtotal >= 0),
  total integer not null check (total >= 0),
  public_token uuid unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  menu_item_id text references public.menu_items(id),
  item_name_snapshot text not null,
  price_snapshot integer not null check (price_snapshot >= 0),
  quantity integer not null check (quantity > 0),
  line_total integer not null check (line_total >= 0)
);

create table public.restaurant_settings (
  id text primary key default 'default' check (id = 'default'),
  restaurant_name text not null,
  city text not null,
  address text,
  phone text,
  whatsapp text,
  instagram_url text,
  two_gis_url text,
  working_hours text,
  delivery_minimum integer not null default 0,
  delivery_text text,
  currency text not null default 'KZT',
  default_language text not null default 'ru',
  notification_sound boolean not null default true,
  updated_at timestamptz not null default now()
);

create table public.promotions (
  id text primary key,
  title_ru text not null,
  title_kk text,
  description_ru text,
  description_kk text,
  image_url text,
  start_date date,
  end_date date,
  is_active boolean not null default false,
  status public.promotion_status not null default 'draft',
  minimum_order integer,
  promotion_type text not null,
  needs_review boolean not null default false,
  is_archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_menu_items_category_visible on public.menu_items(category_id, sort_order) where is_archived = false;
create index idx_menu_items_review on public.menu_items(needs_review) where needs_review = true;
create index idx_orders_status_created on public.orders(status, created_at desc);
create index idx_orders_type_created on public.orders(order_type, created_at desc);
create index idx_order_items_order on public.order_items(order_id);

create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;

create or replace function public.next_order_number(p_order_type text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  sequence_value bigint;
  local_date text;
begin
  if p_order_type = 'delivery' then
    sequence_value := nextval('public.delivery_order_seq');
    local_date := to_char(now() at time zone 'Asia/Qyzylorda', 'YYYYMMDD');
    return 'TQ-' || local_date || '-' || lpad(sequence_value::text, 3, '0');
  elsif p_order_type = 'dine_in' then
    sequence_value := nextval('public.dine_in_order_seq');
    return 'D-' || lpad(sequence_value::text, 3, '0');
  end if;
  raise exception 'Unsupported order type';
end;
$$;

revoke execute on function public.next_order_number(text) from public, anon, authenticated;
grant execute on function public.next_order_number(text) to service_role;
create trigger categories_updated before update on public.categories for each row execute function public.set_updated_at();
create trigger menu_items_updated before update on public.menu_items for each row execute function public.set_updated_at();
create trigger tables_updated before update on public.tables for each row execute function public.set_updated_at();
create trigger orders_updated before update on public.orders for each row execute function public.set_updated_at();
create trigger settings_updated before update on public.restaurant_settings for each row execute function public.set_updated_at();
create trigger promotions_updated before update on public.promotions for each row execute function public.set_updated_at();

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path = public as $$
  select exists(select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.menu_items enable row level security;
alter table public.set_items enable row level security;
alter table public.tables enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.restaurant_settings enable row level security;
alter table public.promotions enable row level security;

create policy "public reads visible categories" on public.categories for select using (is_visible and not is_archived);
create policy "public reads visible menu" on public.menu_items for select using (not is_archived and (is_visible_public or is_visible_dine_in));
create policy "public reads active tables" on public.tables for select using (is_active and not is_archived);
create policy "public reads active settings" on public.restaurant_settings for select using (true);
create policy "public reads active promotions" on public.promotions for select using (is_active and status = 'active' and not is_archived);

create policy "admins manage profiles" on public.profiles for all using (public.is_admin()) with check (public.is_admin());
create policy "admins manage categories" on public.categories for all using (public.is_admin()) with check (public.is_admin());
create policy "admins manage menu" on public.menu_items for all using (public.is_admin()) with check (public.is_admin());
create policy "admins manage set items" on public.set_items for all using (public.is_admin()) with check (public.is_admin());
create policy "admins manage tables" on public.tables for all using (public.is_admin()) with check (public.is_admin());
create policy "admins manage orders" on public.orders for all using (public.is_admin()) with check (public.is_admin());
create policy "admins manage order items" on public.order_items for all using (public.is_admin()) with check (public.is_admin());
create policy "admins manage settings" on public.restaurant_settings for all using (public.is_admin()) with check (public.is_admin());
create policy "admins manage promotions" on public.promotions for all using (public.is_admin()) with check (public.is_admin());

insert into storage.buckets (id, name, public) values ('menu-images', 'menu-images', true) on conflict (id) do update set public = true;
create policy "public reads menu images" on storage.objects for select using (bucket_id = 'menu-images');
create policy "admins upload menu images" on storage.objects for insert with check (bucket_id = 'menu-images' and public.is_admin());
create policy "admins update menu images" on storage.objects for update using (bucket_id = 'menu-images' and public.is_admin());
create policy "admins delete menu images" on storage.objects for delete using (bucket_id = 'menu-images' and public.is_admin());

alter publication supabase_realtime add table public.orders;
